// Converts cert.pem/key.pem (generated by gen_cert.ps1) into cert.h, a C
// header with embedded byte arrays the sketch includes directly.
const fs = require('fs');
const path = require('path');

function toCArray(filePath, varName) {
  let data = fs.readFileSync(filePath);
  if (data[data.length - 1] !== 0) {
    data = Buffer.concat([data, Buffer.from([0])]);
  }
  const lines = [];
  lines.push(`static const uint8_t ${varName}[] = {`);
  for (let i = 0; i < data.length; i += 16) {
    const chunk = data.subarray(i, i + 16);
    const hex = Array.from(chunk).map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ');
    lines.push('  ' + hex + ',');
  }
  lines.push('};');
  lines.push(`static const unsigned int ${varName}_len = ${data.length};`);
  return lines.join('\n');
}

const dir = __dirname;
let out = '#pragma once\n#include <stdint.h>\n\n';
out += toCArray(path.join(dir, 'cert.pem'), 'server_cert_pem') + '\n\n';
out += toCArray(path.join(dir, 'key.pem'), 'server_key_pem') + '\n';
fs.writeFileSync(path.join(dir, 'cert.h'), out);
console.log('cert.h written');
